name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_then_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile.dev --tag mahmoudzidan/docker-react
        docker run -e CI=true mahmoudzidan/docker-react npm run test -- --coverage
